### ISSUE TITLE
cannot run polylidar-simple

### ISSUE THREAD

**Issue by maxwellfrom** [JeremyBYU/polylidar#1]
Hi, 
   I have compiled successfully, however I can't run polylidar-simple, cloud you please tell me what's the problem?

recent:///caaa6a1ad59055fe9355edc15ea904c1

**Comment by maxwellfrom** [comment]
![Screenshot from 2020-04-29 12-27-43](https://user-images.githubusercontent.com/30398190/80561262-70868880-8a16-11ea-9dd2-c9beac66b641.png)

**Comment by maxwellfrom** [comment]
fulong@fulong:~/mfl/polylidar/build$ ./polylidar-simple 
Simple C++ Example of Polylidar
unable to open file for input

**Comment by JeremyBYU** [comment]
Sorry about that! I gave a lot more attention to the python examples and did not do a good job making the single C++ example more clear and *actually simple*.  

The error is complaining that it can't find a test file which is hardcoded here: 
https://github.com/JeremyBYU/polylidar/blob/8473ee54e1553d64da90b7f0c42774fd625cf68d/examples/cpp/simple.cpp#L65

Attached is this file (zipped, so you will have to unzip). Its just a simple 3D point cloud (I believe synthetically generated, its been so long!). Just ensure that you place the file such that it can find it in the path. Example output:
```
(base) ➜  polylidar-old git:(master) ✗ ./build/polylidar-simple                            
Simple C++ Example of Polylidar
Polylidar took 50 milliseconds processing a 100000 point cloud
Point indices of Polygon Shell: [61623,60795,38194,97781,32559,64815,88881,91872,84436,45167,79655,81210,45490,78105,29251,68726,29625,68208,39233,64840,31785,82186,76362,37559,20150,64722,18566,78240,14855,70259,74856,81869,64913,36184,2221,43314,34159,74557,49973,28819,64682,33302,97632,99786,41041,84447,3404,80415]

Detailed timings in milleseconds:
Delaunay Triangulation: 40.38; Mesh Extraction: 8.36; Polygon Extraction: 1.53
(base) ➜  polylidar-old git:(master) ✗ ls tests/fixtures/100K_array_3d.csv 

```
[100K_array_3d.zip](https://github.com/JeremyBYU/polylidar/files/4550264/100K_array_3d.zip)

Just a note: I am completely rewriting Polylidar and work is ongoing in the branch `major_changes_refactor`. In the branch I will make sure that the C++ examples are actually simpler and don't require any magical file thats only on my computer. Some of my test files are quite big and I was worried about including them into version control. I think the big mistake is using a private test file inside of a public example.

**Comment by maxwellfrom** [comment]
> Sorry about that! I gave a lot more attention to the python examples and did not do a good job making the single C++ example more clear and _actually simple_.
> 
> The error is complaining that it can't find a test file which is hardcoded here:
> 
> https://github.com/JeremyBYU/polylidar/blob/8473ee54e1553d64da90b7f0c42774fd625cf68d/examples/cpp/simple.cpp#L65
> 
> Attached is this file (zipped, so you will have to unzip). Its just a simple 3D point cloud (I believe synthetically generated, its been so long!). Just ensure that you place the file such that it can find it in the path. Example output:
> 
> ```
> (base) ➜  polylidar-old git:(master) ✗ ./build/polylidar-simple                            
> Simple C++ Example of Polylidar
> Polylidar took 50 milliseconds processing a 100000 point cloud
> Point indices of Polygon Shell: [61623,60795,38194,97781,32559,64815,88881,91872,84436,45167,79655,81210,45490,78105,29251,68726,29625,68208,39233,64840,31785,82186,76362,37559,20150,64722,18566,78240,14855,70259,74856,81869,64913,36184,2221,43314,34159,74557,49973,28819,64682,33302,97632,99786,41041,84447,3404,80415]
> 
> Detailed timings in milleseconds:
> Delaunay Triangulation: 40.38; Mesh Extraction: 8.36; Polygon Extraction: 1.53
> (base) ➜  polylidar-old git:(master) ✗ ls tests/fixtures/100K_array_3d.csv 
> ```
> 
> [100K_array_3d.zip](https://github.com/JeremyBYU/polylidar/files/4550264/100K_array_3d.zip)
> 
> EDIT - Just realized that this file is included in the git repository! However the path is still hardcoded and assumes that you are running from the main directory (e.g. `polylidar` directory itself).
> 
> Just a note: I am completely rewriting Polylidar and work is ongoing in the branch `major_changes_refactor`. In the branch I will make sure that the C++ examples are actually simpler and don't require any magical file thats only on my computer.

Thanks for your reply, it resolved my problem.

**Comment by JeremyBYU** [comment]
No problem. I also pushed a change to master with a simpler example that doesn't need a file. Thanks for your interest.
