### ISSUE TITLE
Error when importing MatrixDouble

### ISSUE THREAD

**Issue by aldomhm** [JeremyBYU/polylidar#15]
I followed the steps on [Polylidar3D](https://jeremybyu.github.io/polylidar/install_instructions.html#id1) installation. But get the error
ImportError: cannot import name 'MatrixDouble'
when running the line  

from polylidar import MatrixDouble, Polylidar3D

I am currently running Python version 3.6.13 on a Windows 11 OS with an x86_64 architecture. I am utilizing WSL to run the Python environment.

**Comment by JeremyBYU** [comment]
Polylidar now requires python version 3.7 or higher.  Pypi has the binary wheels for 3.7 available for polylidar version 1.09: https://pypi.org/project/polylidar/1.0.9/#files

You should be able to just: `pip install polylidar`
