### ISSUE TITLE
Fixtures download link is broken

### ISSUE THREAD

**Issue by laser101** [JeremyBYU/polylidar#18]
The [installation instructions](https://jeremybyu.github.io/polylidar/install_instructions.html#id1) provide a [link](https://drive.google.com/file/d/1T5u7Cn8H_rWZpugcr_h3VrRx_onTpcX7/view?usp=sharinghttps://drive.google.com/file/d/1T5u7Cn8H_rWZpugcr_h3VrRx_onTpcX7/view?usp=sharing) to download the Example\Fixture\Data  from GoogleDrive, but unfortunately this link is not working.

Is there an alternative download link?

Thank you.

**Comment by JeremyBYU** [comment]
Hi @laser101 . Looks like I may have accidentally deleted the data. Good thing I keep backups! Here is a new link to the data:
https://drive.google.com/file/d/1KDEGZQe4sdO4QIY8sAMceExdK-jey7s6/view?usp=drive_link

**Comment by laser101** [comment]
Great, thanks Jeremy.
