### ISSUE TITLE
What is the role of the parameter alpha=0.0 and lmax=1.0 for extractPolygons?

### ISSUE THREAD

**Issue by ibrahimLearning** [JeremyBYU/polylidar#2]
Thanks for the awesome repo.
I used the extractPolygons. In some data, the function can extract polygon, but in some cases, it returns empty?
I don't understand, why? is there role of the mentioned parameters?

**Comment by JeremyBYU** [comment]
Thanks for checking out Polylidar. Sorry I have not done a great job at documenting the API. This will be done in my next update.

Only one of those parameters should be non-zero at a time. If one is 0 it will be ignored. They are both used to filter out triangles in the mesh to create the "shape" of the point set. So choose to use one or the other based on your needs.


Alpha - This determines the largest circumcircle  radius of a triangle. It will perform filtering the same way as alpha shapes. Note in my implementation alpha **is** the radius.
https://en.m.wikipedia.org/wiki/Alpha_shape
https://doc.cgal.org/latest/Alpha_shapes_2/index.html

Lmax - this is represents the longest allowable edge for a triangle in the mesh. If a triangle has an edge greater than lmax it is filtered.


I personally use just lmax and set alpha to 0. I like having explicit control of the longest distance between points .

Hope this helps!
