### ISSUE TITLE
 Python Installation: No module named 'polylidar.polylidar'

### ISSUE THREAD

**Issue by mwussow** [JeremyBYU/polylidar#6]
I am trying to install the polylidar python package on Windows (Python 3.7; conda 4.9.2).
I first `conda install shapely` (version 1.7.1) and then `pip install polylidar` (version 0.0.8).

The installations seem to succeed. However, when I try to import polylidar in Python, I get the following error message: `ModuleNotFoundError: No module named 'polylidar.polylidar'`

I highly appreciate any advice, thanks in advance!

**Comment by JeremyBYU** [comment]
Thanks for checking out the project. You can't install from pip anymore. Please read the installation instructions in the website:https://jeremybyu.github.io/polylidar/

Basically need to build from source.
Thanks
