### ISSUE TITLE
ImportError: No module named tests.python.helpers.utils

### ISSUE THREAD

**Issue by Yaccoub** [JeremyBYU/polylidar#8]
**Describe the bug**
Trying to run the python example robust.py throws an error `Traceback (most recent call last):
  File "robust.py", line 7, in <module>
    from tests.python.helpers.utils import load_csv
ModuleNotFoundError: No module named 'tests'`

I have built everything from the source and did not install using pip command 

**Environment  (please complete the following information):**
 - OS:  WIndows10 and Ubuntu 18.04
 
Thanks in advance

**Comment by JeremyBYU** [comment]
If you are running `robust.py` it is expecting it to be run from the `polylidar` working directory. In other word you should run `python -m examples.python.robust` from INSIDE the `polylidar` folder.
